theme: jekyll-theme- Minimal Mistakes
title: "Base-Free Adaptive Tracking, Depth Occlusion, and Kinematic AR for Virtual Production"
description: "Medialogy MSc | Aalborg University Copenhagen | Muhannad Al Ulaby"