services:
  # Temporal synchronizer
  sync:
    build: .
    container_name: temporal_alignment

    command: tail -f /dev/null
    volumes:
      - ./data:/VP_AR_full_System_dockerized/data
      - ./temporal_alignment:/VP_AR_full_System_dockerized/temporal_alignment
      - ./run_temporal.sh:/VP_AR_full_System_dockerized/run_temporal.sh
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  # Spatial calibrator
  align:
    build: .
    container_name: spatial_alignment
    command: tail -f /dev/null
    volumes:
      - ./data:/VP_AR_full_System_dockerized/data
      - ./spatial_alignment:/VP_AR_full_System_dockerized/spatial_alignment
      - ./run_spatial.sh:/VP_AR_full_System_dockerized/run_spatial.sh
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]